<div id="titlecenter" class="center"> 
	<span class="title">miniBGG</span><br/> 
	<span class="centersmall"><em>The mobile BoardGameGeek browser</em></span> 
</div> 
<form method="get" action="<?= $this->url(array('controller' => 'search'), 'default', true)?>"> 
	<p class="center"> 
		<label for="input.search">Search:</label><br/> 
		<input id="input.search" name="search"/><br/> 
		<input id="input.submit" type="submit" value="Search"/><br/> 
		<label for="exact">Exact search</label><input type="checkbox" id="exact" name="exact" value="1"/> 
	</p> 
</form> 
<p class="centersmall"> 
	<a href="http://beefsack.com">beefsack.com</a><br/> 
	<a href="http://www.boardgamegeek.com/thread/464899">Discussion Thread</a> 
</p> 
