<? $average = (float) $this->data->boardgame[0]->statistics->ratings->average ?>
<div id="titlecenter" class="center"><h3><?= $this->data->boardgame[0]->name[0] ?></h3></div> 
		<p class="center"><?= round($average, 2) ?> / 10 (<?= $this->data->boardgame[0]->statistics->ratings->usersrated ?> Ratings)<br /> 
<? for ($i = 0; $i < (int) $average; $i++): ?><img src="<?= PUBLIC_PATH ?>img/star_yellow.gif" alt="*" /><? endfor ?><? if ($average - floor($average) <= 0.25): ?><img src="<?= PUBLIC_PATH ?>img/star_white.gif" alt="-" /><? elseif ($average - floor($average) <= 0.75): ?><img src="<?= PUBLIC_PATH ?>img/star_yellowhalf.gif" alt="*" /><? else: ?><img src="<?= PUBLIC_PATH ?>img/star_yellow.gif" alt="*" /><? endif ?><? for ($i = 0; $i < 10 - ceil((float) $average); $i++): ?><img src="<?= PUBLIC_PATH ?>img/star_white.gif" alt="-" /><? endfor ?></p>
		<p class="center"><strong><? if ($this->data->boardgame[0]->statistics->ratings->ranks[0]->rank == '0'): ?>No Rank<? else: ?>Rank: <?= $this->data->boardgame[0]->statistics->ratings->ranks[0]->rank ?><? endif; ?></strong></p> 
	<div class="center"><img src="<?= $this->data->boardgame[0]->thumbnail ?>" alt="Game Image" /></div><br /> 
	<table class="blockcenter"> 
		<tr> 
			<td class="comparetitlesmall">Options</td> 
		</tr> 
		<tr> 
			<td class="comparecell"> 
				<a href="http://www.boardgamegeek.com/boardgame/<?= $this->data->boardgame[0]['objectid'] ?>">Original BGG page</a><br/> 
				<a href="<?= $this->url(array('controller' => 'boardgame', 'action' => 'log', 'objectid' => $this->data->boardgame[0]['objectid'], 'objectname' => $this->data->boardgame[0]->name[0]), 'default', true) ?>">Log play</a>
			</td> 
		</tr> 
	</table> 
	<div class="center"><h4>Information</h4></div> 
	<table class="blockcenter"> 
		<tr> 
			<td class="infotitle">Designer</td> 
			<td class="infocell"><?= ($this->data->boardgame[0]->boardgamedesigner instanceof SimpleXMLElement) ? $this->xmlImplode('<br />', $this->data->boardgame[0]->boardgamedesigner) : $this->data->boardgame[0]->boardgamedesigner ?></td> 
		</tr> 
		<tr> 
			<td class="infotitle">Publisher</td> 
			<td class="infocell"><?= ($this->data->boardgame[0]->boardgamepublisher instanceof SimpleXMLElement) ? $this->xmlImplode('<br />', $this->data->boardgame[0]->boardgamepublisher) : $this->data->boardgame[0]->boardgamepublisher ?></td> 
		</tr> 
		<tr> 
			<td class="infotitle">Players</td> 
			<td class="infocell"><?= $this->data->boardgame[0]->minplayers ?> - <?= $this->data->boardgame[0]->maxplayers ?></td> 
		</tr> 
		<tr> 
			<td class="infotitle">Time</td> 
			<td class="infocell"><?= $this->data->boardgame[0]->playingtime ?> Minutes</td> 
		</tr> 
		<tr> 
			<td class="infotitle">Published</td> 
			<td class="infocell"><?= $this->data->boardgame[0]->yearpublished ?></td> 
		</tr> 
		<? if (isset($this->data->boardgame[0]->boardgamecategory)): ?>
		<tr> 
			<td class="infotitle">Category</td> 
			<td class="infocell"><?= ($this->data->boardgame[0]->boardgamecategory instanceof SimpleXMLElement) ? $this->xmlImplode('<br />', $this->data->boardgame[0]->boardgamecategory) : $this->data->boardgame[0]->boardgamecategory ?></td> 
		</tr> 
		<? endif ?>
		<? if (isset($this->data->boardgame[0]->boardgamemechanic)): ?>
		<tr> 
			<td class="infotitle">Mechanic</td> 
			<td class="infocell"><?= ($this->data->boardgame[0]->boardgamemechanic instanceof SimpleXMLElement) ? $this->xmlImplode('<br />', $this->data->boardgame[0]->boardgamemechanic) : $this->data->boardgame[0]->boardgamemechanic ?></td> 
		</tr> 
		<? endif ?>
		<tr> 
			<td class="infotitle">Names</td> 
			<td class="infocell"><?= ($this->data->boardgame[0]->name instanceof SimpleXMLElement) ? $this->xmlImplode('<br />', $this->data->boardgame[0]->name) : $this->data->boardgame[0]->name ?></td> 
		</tr> 
		<? if (isset($this->data->boardgame[0]->boardgameexpansion)): ?>
		<tr> 
			<td class="infotitle">Expansions</td> 
			<td class="infocell"><?= ($this->data->boardgame[0]->boardgameexpansion instanceof SimpleXMLElement) ? $this->xmlImplode('<br />', $this->data->boardgame[0]->boardgameexpansion, '<a href="'.preg_replace('/expansionobjectid/', '{objectid}', $this->url(array('controller' => 'boardgame', 'action' => 'expansionobjectid'), 'default', true)).'">{elementContent}</a>') : $this->data->boardgame[0]->boardgameexpansion ?></td> 
		</tr> 
		<? endif ?>
	</table> 
	<div class="center"><h4>Description</h4></div> 
	<p class="gamedescription"><?= nl2br($this->data->boardgame[0]->description) ?></p>
	<div class="center"><h4>Stats</h4></div> 
	<table class="blockcenter"> 
		<tr> 
			<td class="infotitle">Bayes Avg.</td> 
			<td class="infocell"><?= round((float) $this->data->boardgame[0]->statistics->ratings->bayesaverage, 2) ?></td> 
		</tr> 
		<tr> 
			<td class="infotitle">Std. Dev.</td> 
			<td class="infocell"><?= round((float) $this->data->boardgame[0]->statistics->ratings->stddev, 2) ?></td> 
		</tr> 
		<tr> 
			<td class="infotitle">Avg. Weight</td> 
			<td class="infocell"><?= round((float) $this->data->boardgame[0]->statistics->ratings->averageweight, 2) ?></td> 
		</tr> 
		<tr> 
			<td class="infotitle">Comments</td> 
			<td class="infocell"><?= $this->data->boardgame[0]->statistics->ratings->numcomments ?></td> 
		</tr> 
		<tr> 
			<td class="infotitle">Owned</td> 
			<td class="infocell"><?= $this->data->boardgame[0]->statistics->ratings->owned ?></td> 
		</tr> 
		<tr> 
			<td class="infotitle">Trading</td> 
			<td class="infocell"><?= $this->data->boardgame[0]->statistics->ratings->trading ?></td> 
		</tr> 
		<tr> 
			<td class="infotitle">Wanting</td> 
			<td class="infocell"><?= $this->data->boardgame[0]->statistics->ratings->wanting ?></td> 
		</tr> 
		<tr> 
			<td class="infotitle">Wishing</td> 
			<td class="infocell"><?= $this->data->boardgame[0]->statistics->ratings->wishing ?></td> 
		</tr> 
	</table> 
	<p class="centersmall"></p> 
		<form id="form.search" method="get" action="<?= $this->url(array('controller' => 'search'), 'default', true)?>"> 
			<p class="center"> 
				<label for="input.search">Compare:</label><br/> 
				<input id="input.search" name="search" title="Search"/><br/> 
				<input id="input.objectid" name="objectid" value="<?= $this->data->boardgame[0]['objectid'] ?>" type="hidden"/> 
				<input id="input.submit" title="Submit button" type="submit" value="Submit"/><br/> 
				<label for="exact">Exact search</label><input type="checkbox" id="exact" name="exact" value="1"/> 
			</p> 
		</form> 